### ISSUE TITLE
"CKEDITOR_BASEPATH" doesn't work correctly

### ISSUE THREAD

**Issue by Naggi-Goishi** [galetahub/ckeditor#707]
## Using
Rails 5.0.0.1
ruby 2.3.1p112
ckeditor-4.2.0

## Bug
Even though `CKEDITOR_BASEPATH` is `/assets/ckeditor`, ckeditor is still searching `assets/javascript/ckeditor`.

## For example, 
When I put my downloaded skin at `/assets/ckeditor/skins`, the console gives me this 404 error
![screenshot 2016-12-08 14 31 15](https://cloud.githubusercontent.com/assets/16622734/21030426/3d00d620-bd53-11e6-9caf-517a2aef62f7.png)

It looks like searching under `/assets/ckeditor/skins`.
However, when I put my skin `/assets/javascripts/ckeditor/skins`, it works.

**Comment by richpeck** [comment]
Exact problem I had the other day, spent 2 days fixing.

You need to reset the tmp cache:

    rake assets:clobber
    rake tmp:clear
    rake assets:precompile

Should fix it

**Comment by Naggi-Goishi** [comment]
@richpeck Wow, thank you for giving me the solution!

**Comment by hussyn12** [comment]
@richpeck  i tried everything you suggest but i still get this error on my production server Uncaught TypeError: Cannot set property 'dir' of undefined.

**Comment by richpeck** [comment]
Can you post the log? And also which server are you using? Heroku or another?

**Comment by Michsior14** [comment]
Tried every thing and I've the same error with dir:

Uncaught TypeError: Cannot set property 'dir' of undefined
    at Object.t (application-401b9cc….js:8)
    at d (application-401b9cc….js:8)
    at Array.u (application-401b9cc….js:8)
    at h (application-401b9cc….js:8)
    at HTMLScriptElement.CKEDITOR.env.ie.a.$.onerror (application-401b9cc….js:8)

Also custom config doesn't work:
/assets/ckeditor/config.js?t=GB8C - 404
/assets/ckeditor/skins/moono-lisa/editor.css?t=GB8C - 404

Only on staging deployed with Capistrano.

**Comment by PirunSeng** [comment]
I've just come up the same problem.
@Naggi-Goishi May you state the exact solution you have tried successfully please?
@Michsior14 Which version works fine for you? I'm using the version maping to repo, too but still no luck.

**Comment by wcmolina** [comment]
I'm having the exact same problem. I tried @richpeck solution but the issue persists. I'm using Rails 5.0.1, Ruby 2.3.3, and ckeditor gem 4.2.2. I'm trying to deploy to my local virtual machine (Ubuntu 16.04) but I can't get ckeditor working. These are the errors I'm getting in the console:

```
GET http://localhost:3000/assets/ckeditor/config.js?t=GB8C 404 (Not Found)
GET http://localhost:3000/assets/ckeditor/skins/moono-lisa/editor.css?t=GB8C 
GET http://localhost:3000/assets/ckeditor/lang/en.js?t=GB8C 
Uncaught TypeError: Cannot set property 'dir' of undefined
    at Object.t (admin-75da25a….js:8)
    at d (admin-75da25a….js:9)
    at Array.u (admin-75da25a….js:9)
    at h (admin-75da25a….js:9)
    at HTMLScriptElement.CKEDITOR.env.ie.a.$.onerror
```

In `assets.rb` I included this line `Rails.application.config.assets.precompile += %w( ckeditor/* )` as suggested in the docs but still doesn't work. I also added the `basepath.js.erb` file, with no luck.

**Comment by Michsior14** [comment]
@PirunSeng 
I've added to gem file: `gem 'ckeditor', github: 'galetahub/ckeditor'`.
Version from bundler is [11d3a5b90564](https://github.com/galetahub/ckeditor/commit/11d3a5b905646c6fd397f7710f95fb9eb29f0865)

**Comment by wcmolina** [comment]
@Michsior14 wow! It works indeed! Thank you so much! I was thinking maybe this issue is related to #716?

**Comment by Michsior14** [comment]
@wcmolina 
Yep it is, but the fix just hasn't been released yet.

**Comment by PirunSeng** [comment]
@Michsior14 Thanks for your reply. Honestly, I don't really understand what you mean by 

> Version from bundler is 11d3a5b90564

I guess you mean to run the rake task, don't you?

**Comment by Michsior14** [comment]
@PirunSeng 
You've asked about gems git revision so I wrote my current version taken from bundler (`bundler show ckeditor`).

**Comment by PirunSeng** [comment]
@Michsior14 
Oh, I see. I didn't know about `bundler show ckeditor` command.

**Comment by ankitsinghaniyaz** [comment]
Still facing the same problem on production
