### ISSUE TITLE
"Failed to load resource" in production only

### ISSUE THREAD

**Issue by thelamborghinistory** [galetahub/ckeditor#719]
Since I updated Rails to 5.0 (and respectively ckeditor to the newest after whatever it was before), I have troubles with the editor in the production environment only. My browser console spits out the following:

> Failed to load resource: the server responded with a status of 404 (Not Found)
> http://myproductionurl.com/assets/ckeditor/plugins/scayt/skins/moono-lisa/scayt.css Failed to load resource: the server responded with a status of 404 (Not Found)
> http://myproductionurl.com/assets/ckeditor/plugins/wsc/skins/moono-lisa/wsc.css Failed to load resource: the server responded with a status of 404 (Not Found)
> http://myproductionurl.com/assets/ckeditor/plugins/copyformatting/lang/en.js?t=GB8C Failed to load resource: the server responded with a status of 404 (Not Found)
> application-d8fde07….js:166 Uncaught TypeError: Cannot read property 'label' of undefined
>     at Object.init (application-d8fde07….js:166)
>     at Object.<anonymous> (application-d8fde07….js:155)
>     at f (application-d8fde07….js:155)
>     at Array.C (application-d8fde07….js:155)
>     at u (application-d8fde07….js:155)
>     at HTMLScriptElement.A.CKEDITOR.env.ie.f.$.onerror (application-d8fde07….js:155)
> http://myproductionurl.com/assets/ckeditor/plugins/copyformatting/styles/copyformatting.css Failed to load resource: the server responded with a status of 404 (Not Found)
> http://myproductionurl.com/assets/ckeditor/skins/moono-lisa/editor.css?t=GB8C Failed to load resource: the server responded with a status of 404 (Not Found)
> http://myproductionurl.com/assets/ckeditor/plugins/scayt/skins/moono-lisa/scayt.css Failed to load resource: the server responded with a status of 404 (Not Found)
> http://myproductionurl.com/assets/ckeditor/plugins/copyformatting/styles/copyformatting.css Failed to load resource: the server responded with a status of 404 (Not Found)
> http://myproductionurl.com/assets/ckeditor/plugins/wsc/skins/moono-lisa/wsc.css Failed to load resource: the server responded with a status of 404 (Not Found)

Fun fact: I am using the ckeditor also for some fields in Rails Admin, where it works perfectly. I seem to have built the ckeditor in the custom part of the site wrongly, but it's still weird cause it used to work with the current integration (I have `ckeditor/*` in my precompile paths and in my app.js I have 
```
//= require ckeditor/init
//= require ckeditor/config
```
In the view I am calling the editor like
`= f.cktext_area "body_#{l}"` (Slim Syntax)
as well.) Am I overseeing something?

**Comment by ACPK** [comment]
Same issue.

**Comment by macowie** [comment]
I'm also seeing this in production.

![screen shot 2017-01-11 at 10 03 18 am](https://cloud.githubusercontent.com/assets/2200578/21856368/661b8830-d7e7-11e6-9ccf-f97ead61224c.png)

**Comment by jrochkind** [comment]
I have worked around by using a custom rake task to copy non-digest-fingerprinted asset filenames. Approach (and other approaches) detailed at https://bibwild.wordpress.com/2014/10/02/non-digested-asset-names-in-rails-4-your-options/

**Comment by patricklindsay** [comment]
This has been fixed in #716. It just hasn't been released yet.

**Comment by thelamborghinistory** [comment]
I already checked out the master, almost every file works now. There is one thing though that still doesn't work (I assume the second error will disappear after the file becomes available):

```
http://myproductionurl.com/assets/ckeditor/plugins/copyformatting/lang/en.js?t=GB8C Failed to load resource: the server responded with a status of 404 (Not Found)

application-d8fde07….js:166 Uncaught TypeError: Cannot read property 'label' of undefined
at Object.init (application-d8fde07….js:166)
at Object. (application-d8fde07….js:155)
at f (application-d8fde07….js:155)
at Array.C (application-d8fde07….js:155)
at u (application-d8fde07….js:155)
at HTMLScriptElement.A.CKEDITOR.env.ie.f.$.onerror (application-d8fde07….js:155)
```

**Comment by ttibau** [comment]
+1

**Comment by voodoorai2000** [comment]
+1

**Comment by voodoorai2000** [comment]
Works for us using: 
gem 'ckeditor', git: "https://github.com/galetahub/ckeditor.git"

**Comment by kevonc** [comment]
Same issue, use the latest version works
1) gem 'ckeditor', github: 'galetahub/ckeditor'
2) bundle update
:)

**Comment by thelamborghinistory** [comment]
Yep, works now for me, too. I guess I can close this now?

**Comment by sheharyarn** [comment]
I think this should remain open until a new release containing the patch is created. I spent over 10 hours trying to 'fix' this not realizing this was a bug in the library.

**Comment by feliperaul** [comment]
@mxmzb I agree with @sheharyarn and also spent over 5 hours ... could you guys please create a new release?

**Comment by galetahub** [comment]
Just released new gem version

**Comment by JacobRWall** [comment]
this is happening to me currently with ckeditor4-vue, is anyone here still alive?
